### ISSUE TITLE
[Debugger] "Can only iterate over an array or an instance of java.lang.Iterable" shown sometimes

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.debug#102]
When I click on a Set, e.g. a LinkedHashSet in the "Variables" view of the debugger sometimes it shows
```
Detail formatter error:
		Can only iterate over an array or an instance of java.lang.Iterable
```
So far I cannot reproduce this reliably, but it occurs fairly often (multiple times a day).

This happens with version 2022-06 (4.24.0) on macOS.

The interesting thing is that the debugger actually understands that the variable is a  Set. With "Show logical structure" the content of the set is correctly shown. Just the details when clicking on the set is wrong.

The error log does not show entries.

**Comment by jukzi** [comment]
This issues does not contain necessary information to reproduce. please reopen if you can provide steps to reproduce - even if it happens only randomly. You may also contribute a PR to make the error message to contain more relevant information.

**Comment by jubax** [comment]
@jukzi, this still happens from time to time, but I cannot reproduce it in a reliable way. Do you have any hints on how to gather useful information for reproducing it? Turn on some logging? Something else?
