### ISSUE TITLE
Add Double click listener to AllInstances and AllReferences popup to navigate to the implementation 

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#110]
Adding a double click listener to the AllReferencesActionDelegate and AllInstancesActionDelegate,
https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/85/files
https://github.com/eclipse-platform/eclipse.platform.debug/pull/52

**Comment by SarikaSinha** [comment]
@gzsombor 
Thank you!
Please add N&N entry my Monday 15/8.

**Comment by gzsombor** [comment]
I think, this can be closed
