### ISSUE TITLE
improvement: use method name to find unqualified Stacktraces 

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#115]
paste this into Java Stack Trace Console in a Platform SDK workspace:
```
Project.writeDescription(int) line: 1402
```
click the link (feature from https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/5)
![image](https://user-images.githubusercontent.com/51790620/187794875-012168a5-fcfd-42d6-bc51-281db853d2a7.png) 

=> Select type dialog opens. because "Project" is unqualified and could mean various types:
![image](https://user-images.githubusercontent.com/51790620/187794215-14d3e2e6-bf76-457c-9fa7-e38627d42c7f.png)

However the logic could see that only one of those classes has a "writeDescription" method. That logic already exists in the command Navigate/"Open from Clipboard" and does automatically finds and opens the right class.

...
Some types would also not qualify for the link as they are not even 1402 lines long

cc @trancexpress - interested to work on this?

**Comment by SougandhS** [comment]
Hi @mpalat, could you please assign this to me

**Comment by SougandhS** [comment]
Hi @jukzi 
enhancement has been implemented -> [PR@498](https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/498) 
Shall we close this PR now ?

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/543 and issues on https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/544 

Looking on the number of issues I've found above, I will now revert https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/498 PR as 
1) the code has multiple regressions
2) The code in  `org.eclipse.jdt.internal.debug.ui.console.JavaStackTraceHyperlink.searchCompleted(Object, String, int, IStatus)` is simply not maintainable.

Revert PR: https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/545

I would recommend to rewrite https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/498.

Reopening this ticket.
