### ISSUE TITLE
[20] Debug Support for Java 20

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#145]
Root bug for Java 20 Debug support

- [ ] https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/144
- [ ] [20] Add Execution Environment for JavaSE-20
- [ ] [20] Update Javadoc location for Java 20
- [ ] [20] Project Loom Second Preview

**Comment by iloveeclipse** [comment]
@SarikaSinha : is tis done or should it be moved to 4.29 milestone?

**Comment by SarikaSinha** [comment]
Nothing more to be done, closing the issue.
