### ISSUE TITLE
[20] Project Loom Second Preview

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#166]
[JEP 436: Virtual Threads (Second Preview)](https://openjdk.org/jeps/436)
[JEP 437: Structured Concurrency (Second Incubator)](https://openjdk.org/jeps/437)

**Comment by SarikaSinha** [comment]
@testforstephen 
Are you interested in driving this effort?

**Comment by testforstephen** [comment]
yes, I can keep an eye on it and see if there is anything further to do with debugging support.

**Comment by testforstephen** [comment]
- [JEP 436: Virtual Threads (Second Preview)](https://openjdk.org/jeps/436)
> History
Virtual threads were proposed as a preview feature by [JEP 425](https://openjdk.org/jeps/425) and delivered in [JDK 19](https://openjdk.org/projects/jdk/19/). This JEP proposes a second preview to allow time for more feedback and to get more experience with this feature.
>
>Minor changes since the first preview:
>
>A small number of API changes described by JEP 425 were made permanent in JDK 19 and thus are not proposed for preview here. These changes were made permanent because they involve functionality that is broadly useful and is not specific to virtual threads. They consist of new methods in Thread ([join(Duration)](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Thread.html#join(java.time.Duration)), [sleep(Duration)](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Thread.html#sleep(java.time.Duration)), and [threadId()](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/Thread.html#threadId())), new methods in [Future](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/util/concurrent/Future.html) (to examine task state and result), and the change to make [ExecutorService](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/concurrent/ExecutorService.html) extend [AutoCloseable](https://download.java.net/java/early_access/jdk20/docs/api/java.base/java/lang/AutoCloseable.html).
>
>The [degradations to ThreadGroup described in JEP 425](https://openjdk.org/jeps/425#java-lang-ThreadGroup) were made permanent in JDK 19.

See the [comment](https://bugs.openjdk.org/browse/JDK-8295817?focusedCommentId=14532596&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14532596) for the JEP 436, it is mostly a clone of JEP 425, and the only new section is the History section.

It just has some minor changes in the internal API, no additional debugging changes are needed.
   
- [JEP 437: Structured Concurrency (Second Incubator)](https://openjdk.org/jeps/437)
> History
Structured Concurrency was proposed by [JEP 428](https://openjdk.org/jeps/428) and delivered in [JDK 19](https://openjdk.org/projects/jdk/19/) as an incubating API. This JEP proposes to re-incubate the API, without changes, in JDK 20 to allow time for more feedback and to get more experience with this feature.
>
>The only change in the re-incubated API is that [StructuredTaskScope](https://download.java.net/java/early_access/jdk20/docs/api/jdk.incubator.concurrent/jdk/incubator/concurrent/StructuredTaskScope.html) is updated to support the inheritance of scoped values ([JEP 429](https://openjdk.org/jeps/429)) by threads created in a task scope. This streamlines the sharing of immutable data across threads.

See the [comment](https://bugs.openjdk.org/browse/JDK-8296037?focusedCommentId=14533204&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14533204) for the JEP 437,  the only change in this JEP from JEP 428 is the addition of the History section. 

No additional debugging changes are needed.

**Comment by iloveeclipse** [comment]
@SarikaSinha : is this done or should it be moved to 4.29 milestone?

**Comment by SarikaSinha** [comment]
As there were no changes required, closing the issue.
