### ISSUE TITLE
Provide means to query packages exported by the JRE

### ISSUE THREAD

**Issue by HannesWell** [eclipse-jdt/eclipse.jdt.debug#175]
In PDE we have a utility method to obtain the packages packages exported by the JRE of a given `IVMInstall/IExecutionEnvironment`, which is duplicated at multiple locations and also has to access JDT-internals:

https://github.com/eclipse-pde/eclipse.pde/blob/47ef407df3082de87f9e8adc26c517204433ce11/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/TargetPlatformHelper.java#L407-L454

I wonder if we should add a corresponding method to `IVMInstall` or `IExecutionEnvironment`, depending on where you think it fits better that returns a Set of package names exported by the JRE.

**Comment by HannesWell** [comment]
> Looking on your snippet, I think `IExecutionEnvironment` is more suitable, at least slightly adopted snippet compiles inside that interface.

In order to be able to query a specific VMInstall for the packages it provides it would be better to add such a method to the `VMInstall` interface. But then API-tools complain that the interface is intended to be implemented by clients and that even a default method is a breaking-change which requires version 4.
If suppressing that error isn't an option a static method could be added to for example `JavaRuntime` that accepts a `VMInstall` and a release and returns the provided packages.

**Comment by iloveeclipse** [comment]
- `testJavaRuntimeQuerySystemPackages_modularJDK` new test fails **differently** on different OS / Java versions.
- `testJavaRuntimeQuerySystemPackages_nonModularJDK` fails because unable to find Java 8 JVM - I would "assume" Java 1.8 as precondition for this test and/or simply only run in Jenkins (where we have the env.variable specified).

@HannesWell: could you please work on that?

Mac Java 17:
https://download.eclipse.org/eclipse/downloads/drops4/I20240424-1800/testresults/html/org.eclipse.jdt.debug.tests_ep432I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
begin 0, end -1, length 2

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
at java.base/java.lang.String.substring(String.java:2704)
at org.eclipse.jdt.debug.tests.core.VMInstallTests.testJavaRuntimeQuerySystemPackages_modularJDK(VMInstallTests.java:249)
```

```
No non-modular VM (<=Java-1.8) found.

junit.framework.AssertionFailedError: No non-modular VM (<=Java-1.8) found.
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNotNull(Assert.java:256)
at junit.framework.TestCase.assertNotNull(TestCase.java:399)
at org.eclipse.jdt.debug.tests.core.VMInstallTests.searchFirstNonModularVM(VMInstallTests.java:321)
at org.eclipse.jdt.debug.tests.core.VMInstallTests.testJavaRuntimeQuerySystemPackages_nonModularJDK(VMInstallTests.java:264)
```

Linux Java 21 / 22
https://download.eclipse.org/eclipse/downloads/drops4/I20240424-1800/testresults/html/org.eclipse.jdt.debug.tests_ep432I-unit-cen64-gtk3-java21_linux.gtk.x86_64_21.html
```
Range [0, -1) out of bounds for length 2

java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 2
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4861)
at java.base/java.lang.String.substring(String.java:2830)
at org.eclipse.jdt.debug.tests.core.VMInstallTests.testJavaRuntimeQuerySystemPackages_modularJDK(VMInstallTests.java:249)
```

**Comment by HannesWell** [comment]
> @HannesWell: could you please work on that?

Yes, will do it this evening.

**Comment by HannesWell** [comment]
> * `testJavaRuntimeQuerySystemPackages_nonModularJDK` fails because unable to find Java 8 JVM - I would "assume" Java 1.8 as precondition for this test and/or simply only run in Jenkins (where we have the env.variable specified).

I would be in favor of adding the environment variable to the I-builds tests as well.
The reason is that if we use an assumption to disable the tests if the variable is not set the day JDK-8 is not available anymore on Jenkins and that variable is removed the test is silently skipped (unless somebody searches for the the variables string in the repo). But I think it would be better to fail loud in that case so that the future developers (or future us) gets aware of that an entire code path is untested and take the appropriated actions (or do the informed decision to keep it untested).

I'm currently preparing and testing that. If everything goes as planned it should be a simple change like in https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/438 (just for the I-builds).

> begin 0, end -1, length 2

> ```
> Range [0, -1) out of bounds for length 2
> ```

Looks like not all JDKs report versions like `17.0.10`, but some also just report `17`. I'll fix that in the tests.

**Comment by HannesWell** [comment]
> I'm currently preparing and testing that. If everything goes as planned it should be a simple change like in #438 (just for the I-builds).

Well it turned out that the Mac and Windows Test job configurations are not as nice Jenkins pipelines as the Linux ones are so it would require more preparatory work to achieve that goal, which I don't have today.
So for now I just went with the skipping approach if no non-modular JDK is found:
https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/439

If the I-builds are more flexible in this regard one day, this can still be made more strict again.

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20240501-1800/testresults/html/org.eclipse.jdt.debug.tests_ep432I-unit-cen64-gtk3-java22_linux.gtk.x86_64_22.html

`testJavaRuntimeQuerySystemPackages_modularJDK` fails on Java 22:
```
testJavaRuntimeQuerySystemPackages_modularJDK	Failure	expected org.eclipse.core.runtime.CoreException to be thrown, but nothing was thrown

java.lang.AssertionError: expected org.eclipse.core.runtime.CoreException to be thrown, but nothing was thrown
at org.eclipse.jdt.debug.tests.core.VMInstallTests.testJavaRuntimeQuerySystemPackages_modularJDK(VMInstallTests.java:252)
```

`testJavaRuntimeQuerySystemPackages_nonModularJDK` fails on all Java 17 - 21 - 22:
```
got: <[null]>, expected: every item is not null

org.junit.AssumptionViolatedException: got: <[null]>, expected: every item is not null
at org.eclipse.jdt.debug.tests.core.VMInstallTests.searchFirstNonModularVM(VMInstallTests.java:330)
at org.eclipse.jdt.debug.tests.core.VMInstallTests.testJavaRuntimeQuerySystemPackages_nonModularJDK(VMInstallTests.java:266)
```

**Comment by HannesWell** [comment]
Thanks for the heads-up.

> `testJavaRuntimeQuerySystemPackages_modularJDK` fails on Java 22:

I can reproduce that locally when running the tests with a JDK-22.
The reason for the unexpected success is that if `23` is passed as `release`, in
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/68e8c0cdb52504bfafb4b233ac12ae55577fdd45/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/ClasspathLocation.java#L171
`sameRelease` becomes true, because 23 is not yet supported. The reason is that `CompilerOptions.versionToJdkLevel()` defaults to the latest supported version(currently 22), which in turn lets `JavaCore.compareJavaVersions("22", "23")` return `true`. Eventually this means that the JVM is queried without `release` argument.

This could be fixed, by simply skipping that assert if the queried JVM is of the latest supported version (or even newer).


> 
> `testJavaRuntimeQuerySystemPackages_nonModularJDK` fails on all Java 17 - 21 - 22:
> 
> ```
> org.junit.AssumptionViolatedException: got: <[null]>, expected: every item is not null
> ```

The exception is actually expected, but it looks like the I-build tests don't handle these 'Abort'-Exceptions correctly and don't mark the test as skipped. It is the same when reaching that branch in a local execution in the JDE and when using JUnit-5's `Assumptions.assumeTrue()`. I have to admit I'm surprised that this does not work out of the box.
Can you tell if this is handled in JDT or somewhere in JUnit?

**Comment by HannesWell** [comment]
> The exception is actually expected, but it looks like the I-build tests don't handle these 'Abort'-Exceptions correctly and don't mark the test as skipped. It is the same when reaching that branch in a local execution in the JDE and when using JUnit-5's `Assumptions.assumeTrue()`. I have to admit I'm surprised that this does not work out of the box.
> Can you tell if this is handled in JDT or somewhere in JUnit?

OK, it looks like the problem is that the VMInstallTests is still a JUnit-3 test that cannot handle these exceptions.
I'll try to convert it to a JUnit-5 test or is there a reason speaking against such migration?

**Comment by iloveeclipse** [comment]
> I'll try to convert it to a JUnit-5 test or is there a reason speaking against such migration?

Nothing, except that I would prefer to "mute" the tests first, as it would be better to have "green" state before starting (possibly longer) transition.

**Comment by HannesWell** [comment]
> > I'll try to convert it to a JUnit-5 test or is there a reason speaking against such migration?
> 
> Nothing, except that I would prefer to "mute" the tests first, as it would be better to have "green" state before starting (possibly longer) transition.

Understand and Migrating to JUnit-5 is probably more work, but migrating the test to JUnit-4 was straightforward and I pushed it to https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/441.
I have tested the Java-17 and Java-22 VM scenario with and without `NON_MODULAR_JAVA_HOME` available and always without co-located VMs  and in the IDE all worked as expected (i.e. all tests either pass or are properly skipped). So given that the I-build don't use a different mechanism it should now work.

**Comment by HannesWell** [comment]
> `testJavaRuntimeQuerySystemPackages_modularJDK` fails on Java 22:
> 
> `testJavaRuntimeQuerySystemPackages_nonModularJDK` fails on all Java 17 - 21 - 22:

Finally all cases in `VMInstallTests` also pass in the I-build tests.
Thank you Andrey for your help and everybody else involved in resolving this issue.
