### ISSUE TITLE
Enhancement request: Time saver in "run configurations"

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-jdt/eclipse.jdt.debug#178]
I post in the forum an idea that IMHO will be a time saver.

https://www.eclipse.org/forums/index.php/m/1857190/#msg_1857190

There are images that show the current situation and the improvement.

You will also notice the feedback to the idea.

Please take a look and respond.

**Comment by eitan-rosenberg** [comment]
Hi @noopur2507 ,

Are there any plans to implement this Enhancement?

Regards,

**Comment by jjohnstn** [comment]
I'll take a look at it.  I like Ed's suggestion of just using the class qualifier.  I think it would be best to make this an optional preference.

**Comment by eitan-rosenberg** [comment]
Thanks for a quick response.

What is "a fully qualified class name"  ? (For me, it is the result of Class.getName())
Does it contain the project name ?

The reason I think that the project name should be included is that you might have multiple projects open at the same time.

Imagine a case where you duplicate a project under a different name, and you open the original and the copy at the same time. 

I agree that optional preference is best and if you look at the original discussion Ed Merks even suggested using a template.

**Comment by jjohnstn** [comment]
Yes, Class.getName().  IMO, the complexity of a template isn't warranted and most users will be happy with simple qualification.  For those that have some extreme corner cases as you mention, renaming the configuration is very easy in those rare occasions.  I am suggesting implementing the simple solution and let users try it out.  Additional preferences can be added in the future if there is enough demand and the new setting can even be made the default if popular enough.

**Comment by eitan-rosenberg** [comment]
Ok,

I agree, implementing the simple solution (Class.getName()) is best for now(to speed up things....).
As a workaround, I can always add a super package that will include all the other packages.

Thanks and Godspeed.

**Comment by eitan-rosenberg** [comment]
> I have added a JDT UI PR for the preference part of this. At the moment, I have the new preferences under Java -> Launching which is a new page. Right now there is only a Debug category under Java and not a Run/Debug otherwise I would put it there. The preferences are for Java Applications (local and remote), JUnit tests (includes JUnit test, JUnit plugin test, and the new Generic view Junit test, Generic view JUnit plugin test), and Java Applets.
> 
> I will post a debug PR which requires this PR to work for you to try out.

Great news !!!
Thanks.

**Comment by eitan-rosenberg** [comment]
Hi there !
Is there a way for me to test the new stuff ?

**Comment by jjohnstn** [comment]
I just merged the JDT UI stuff and will shortly merge the JDT Debug portion so it should be available via the I-builds on Friday or at worst Saturday.

**Comment by jjohnstn** [comment]
If you check out eclipse.jdt.debug and apply the debug PR and run a child Eclipse you can do so now.

**Comment by eitan-rosenberg** [comment]
Thanks,
I will wait for the I-builds. 
I have to admit that I am a  more of a user of eclipse than a developer.
You have here a 71+ years old retired programmer that use Java as a hobby and 
Brain training.

**Comment by jjohnstn** [comment]
Hi @eitan-rosenberg Patch has been merged.  Should be in the next I-build which you can update from:

https://download.eclipse.org/eclipse/updates/4.28-I-builds

This will update your Eclipse install to 4.28 M1 + patches.  If you are uncomfortable with that, download another 2023-03 Eclipse SDK and update it via the repo above so you can try out the patch without disrupting your current set-up.

**Comment by iloveeclipse** [comment]
Jeff, please provide N&N entry.

**Comment by eitan-rosenberg** [comment]
Good morning. (It is 7:44 in the morning here)
I will try ASAP.
Thanks.

**Comment by jjohnstn** [comment]
@iloveeclipse Will do.

**Comment by eitan-rosenberg** [comment]
> Hi @eitan-rosenberg Patch has been merged. Should be in the next I-build which you can update from:
> 
> https://download.eclipse.org/eclipse/updates/4.28-I-builds
> 
> This will update your Eclipse install to 4.28 M1 + patches. If you are uncomfortable with that, download another 2023-03 Eclipse SDK and update it via the repo above so you can try out the patch without disrupting your current set-up.

Hi,
Firstly many thanks.
Works like a charm... something to show to my grandchildren...
I was wondering how to incorporate this in my current 023-03. Is it possible ?
Is it worth to try adding to eclipse-SDK-4.27 the components that I use ?
regards.

**Comment by jjohnstn** [comment]
Hi @eitan-rosenberg Glad you like it.  If you update your current 2023-03 using 4.28-I-builds, yes you can use the new feature but you will get other platform updates and technically will be somewhere between 2023-03 and 2023-06.  That's not a bad thing.  If you are worried about that, you can always download a 4.28 M2 package when it is available (next week I believe) and start using it alongside your 2023-03.  If you run into some major problem, you will still have your 2023-03 to fall back on.

**Comment by eitan-rosenberg** [comment]
What I did is to download and "install" eclipse-SDK-4.28M1-win32-x86_64.zip and 
add to it : 
- Lombok
- Marketplace Client 
- Eclipse Web Developer Tools.
For me, it is enough.
Today I deleted my 2023-03 folder....
Actually, I think that in the future I will use this approach, so I will have what I actually use.
Thanks again.
