### ISSUE TITLE
Clean up duplicated code in JavaRuntime

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.debug#184]
See `org.eclipse.jdt.launching.JavaRuntime.isModule(IClasspathEntry, IJavaProject)`, the code there can partially be replaced with the new `ClasspathEntry.isModular()`.

**Comment by SarikaSinha** [comment]
@trancexpress @iloveeclipse 
I am seeing this Error:
Description	Resource	Path	Location	Type
The method isModular() in the type ClasspathEntry is not applicable for the arguments (IClasspathEntry)	JavaRuntime.java	/org.eclipse.jdt.launching/launching/org/eclipse/jdt/launching	line 1036	Java Problem

**Comment by iloveeclipse** [comment]
@SarikaSinha : not sure what you mean : do you see it on some private branch, or after merge? Master is error free.

**Comment by SarikaSinha** [comment]
I was facing on master after taking 4.28 but looks like some rebuild issue.
Sorry for the noise.
