### ISSUE TITLE
Add "Enable All" to context menu of Breakpoints view

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.debug#198]
The Breakpoints view has a "Disable All" entry in its context menu, which is very convenient when working with a lot of breakpoints. But its missing an "Enable All" entry:

![breakpoints_view_context_menu](https://user-images.githubusercontent.com/24752155/224569134-83967a7f-6b69-42d8-85ff-4960974f59cf.png)

**Comment by SarikaSinha** [comment]
Common usage is to enable/disable  "Skip Breakpoints"  but we can add here also if it helps.

**Comment by trancexpress** [comment]
> Common usage is to enable/disable "Skip Breakpoints" but we can add here also if it helps.

My use case is, have 15-20 breakpoints and most of the time care only about 2-3 breakpoints. From time to time, enable all breakpoints, debug some and then disable most of the breakpoints again.

Disabling is simple due to the disable all menu entry. Enabling is a lot of clicking in comparison.

**Comment by SougandhS** [comment]
Has implemented now.
https://github.com/eclipse-platform/eclipse.platform/pull/1533

**Comment by trancexpress** [comment]
Thank you @SougandhS !
