### ISSUE TITLE
Compare two strings in debug view

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.debug#203]
One thing I recently missed was that I have a breakpoint where it stops and I have two strings in the variable view.

It would helpful to select two String variables (of course would also be usefull for List, Map, ... ) and choose from the context menu "Compare with each other" and then get a Diff-View

**Comment by SarikaSinha** [comment]
Variable View is provided by Platform debug, so the basic infrastructure to compare two elements should be provided in Platform, JDT might need to add few things to support complex Data Structure comparisons.

**Comment by laeubi** [comment]
Thanks, I now created:
- https://github.com/eclipse-platform/eclipse.platform.debug/issues/121
