### ISSUE TITLE
"Debug As JUnit test" is missing

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#213]
Looking at https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/212 I've tried to run SourceLocationTests from IDE but the "Debug As JUnit test" entry is simply missing.

Have to bisect where it is coming from, probably either from https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/496. I see it with already with eclipse-SDK-I20230323-0850.

Could be also same root cause as https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/212 .

**Comment by iloveeclipse** [comment]
OK, I see it even before JAVA20 branch merge. Probably regression from https://github.com/eclipse-platform/eclipse.platform.debug/pull/122 ?

**Comment by iloveeclipse** [comment]
Using I20230320-1800 no problems: 
![image](https://user-images.githubusercontent.com/964108/227455292-70313086-fadc-47b7-9542-79f5b03c53c6.png)

**Comment by mickaelistria** [comment]
Should be fixed with https://github.com/eclipse-platform/eclipse.platform.debug/pull/125

**Comment by iloveeclipse** [comment]
> Should be fixed with [eclipse-platform/eclipse.platform.debug#125](https://github.com/eclipse-platform/eclipse.platform.debug/pull/125)

Thanks Mickael.
