### ISSUE TITLE
[21] JEP 444: Virtual Threads

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.debug#219]
Ref: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/915
Investigate whether Virtual Threads needs changes in jdt.debug.

**Comment by mickaelistria** [comment]
I just tried using Virtual Threads (over Java 19 though) and I think one issue is that virtual threads are treated as system and thus hidden by default. I would expect those to be visible like regular threads.
Here is the code I used

```java
import java.time.Duration;

public class c {

	public static void main(String[] args) throws InterruptedException {
		Thread t = Thread.startVirtualThread(() -> {
			try {
				Thread.sleep(Duration.ofMinutes(1));
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		});
		t.setName("virtual thread");
		t.join();
	}
}
```

**Comment by iloveeclipse** [comment]
So we will allow to show few billions threads by default?

See also
- https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/38
- https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/76

@SarikaSinha: what was the state of the discussion, how do we want virtual threads to be displayed?

Any limits we might want? Because SWT will surely explode with anything over 5.000 - 10.000 threads.

@trancexpress : FYI.

**Comment by mickaelistria** [comment]
I'm not suggesting to show system threads by default, but isn't there a way to distinguish between "user" virtual threads and "system" ones?

**Comment by trancexpress** [comment]
> @trancexpress : FYI.

There is the filter for suspended threads, that doesn't work properly. It shows some of the inconsistent displayed thread state bugs that  we have fixed previously (but without the filter in use). Maybe it would help, if it worked.

Though I guess a breakpoint can halt thousands of threads too, then the view will likely explode as it would without the filter.

**Comment by testforstephen** [comment]
By default, the current strategy does not show all the running virtual threads, as they could number in the millions. However, it does display the suspended virtual threads (which are usually limited by the CPU cores) in the threads view. I think this is a reasonable approach.

For thread name, we show it as "**System Thread [virtual thread]**". This might cause some confusion, an alternative option could be "**Virtual Thread [#name or #id]**".
![image](https://user-images.githubusercontent.com/14052197/229793298-2f7218fa-6592-4542-a3a5-7e2266dda8b3.png)

**Comment by iloveeclipse** [comment]
@testforstephen : I haven't checked where the "virtual" threads are defined as "system" threads. Is this coming from JDI or is this something we (Eclipse) add on top?

> an alternative option could be "Virtual Thread [#name or #id]".

This sounds better. Would you please provide a PR for that?

**Comment by testforstephen** [comment]
> I haven't checked where the "virtual" threads are defined as "system" threads. Is this coming from JDI or is this something we (Eclipse) add on top?

@iloveeclipse System thread is a concept defined by Eclipse, not from JDI.

> This sounds better. Would you please provide a PR for that?

Ok, I can take a look.

**Comment by SarikaSinha** [comment]
We did not have any concrete decision/discussion on what we want to show. We cannot show all Virtual threads is obvious. Even for a category like suspended or "Platform" or some other in future it might be huge. 
We need to have some provision of pagination for the available threads we want to show or system need to be smart to get the whole no of threads and show only if it is less than "some number"( if pagination is not there).

**Comment by SarikaSinha** [comment]
@testforstephen 
Are you planning to work on this for Java 21 Release?

**Comment by testforstephen** [comment]
From the JDI perspective, there is nothing more to do for JEP 444. 

I suggest we open a new issue to discuss the UX issue about how to present the virtual threads in Eclipse Debug view. And should we just hide all virtual threads by default before we get a conclusion on how to show them?
