### ISSUE TITLE
Update org.eclipse.jdt.launching.javaagent to use ASM 9.5

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#224]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/993

We can update org.eclipse.jdt.launching.javaagent to use ASM 9.5.

**Comment by subyssurendran666** [comment]
PR: https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/243
