### ISSUE TITLE
Detect Java installations from standard folders

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.debug#230]
The use-case is the following:
I have Java 19 installed in standard `/usr/lib/jvm/...` directory and am opening Eclipse IDE hoping to work with Java 19. Then Java 19 doesn't work by default, no compatible runtime is found, classpath entry is unbound.
JDT debug could have some pre-defined standard directories to detect Java installations from; according to the OS, similarly to how it is done for web browsers detection.

**Comment by rgrunber** [comment]
In vscode-java we use an npm library jdk-utils mainly to try to detect a compatible (Java 17) JRE if we're on a platform where we don't ship our own. https://github.com/Eskibear/node-jdk-utils/blob/main/src/index.ts#L81 . Are there any locations in that logic that might be beneficial to add here also ?

@testforstephen, @fbricon this should be a no-op improvement on our end right ? When build support for m2e/gradle detect the source/target, it seems to be matched with the default JDK (eg. 17) (where we don't set `java.configuration.runtimes`). Might this change handle setting it correctly ?

**Comment by fbricon** [comment]
@rgrunber yes jdt.ls will get it for free. 

vscode-java could also ship https://github.com/sidespin/jre-discovery which is a more complete JRE detection solution (extensible, doesn't require restart)

**Comment by basilevs** [comment]
Does it make sense to add `${JAVA_HOME}/..` to root directories?

**Comment by mickaelistria** [comment]
> Does it make sense to add ${JAVA_HOME}/.. to root directories?

Yes, I think so. As I'm now mostly using JustJ, I find the running VM is often missing.
