### ISSUE TITLE
No way to start a process without "-Dfile.encoding" specified

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#24]
I'm trying to debug encoding issues with resources init, and using publicly available tooling (without hacking debugger code) I'm unable to start JVM **without** "-Dfile.encoding" specified, because `org.eclipse.jdt.internal.launching.StandardVMRunner.ensureEncoding(ILaunch, String[])` **always** sets **some** value

because `org.eclipse.debug.internal.core.LaunchConfiguration.launch(String, IProgressMonitor, boolean, boolean)` that always set console encoding to some value 

because `org.eclipse.debug.internal.core.LaunchManager.getEncoding(ILaunchConfiguration)` always returns some value.
That is insane...

**Comment by jukzi** [comment]
Unfortunately that is according to the documented API for both
org.eclipse.debug.core.ILaunchManager.getEncoding(ILaunchConfiguration)
and
org.eclipse.core.resources.ResourcesPlugin.getEncoding()


However i would prefer if the default for launching would be to use NO encoding setting by default.

**Comment by iloveeclipse** [comment]
I haven't checked that deeper, but an explicit option "don't mess up with encoding" is surely possible.

**Comment by jukzi** [comment]
This was fixed with https://github.com/eclipse-platform/eclipse.platform.debug/issues/42. please close.
