### ISSUE TITLE
Preferences - Step Filtering - Defined step filters cannot be stored

### ISSUE THREAD

**Issue by derWallace** [eclipse-jdt/eclipse.jdt.debug#25]
Eclipse version:  2022-03:  
It seems the step filters selected in the Step Filtering Preference page are not shown anymore correctly.    

+ open fresh Eclipse workspace
+ open Step Filtering preference page
+ activate Use Step Fitlers
+ select unselected step filter
+ click on Apply
+ click on Apply and Close
+ open Preferences for Step Filtering again
+ newly selected step filter still is unselected

see also: https://stackoverflow.com/questions/71688010/cant-edit-definded-step-filters-in-eclipse

**Comment by jjohnstn** [comment]
This was fixed by Bug 576615 - https://bugs.eclipse.org/bugs/show_bug.cgi?id=576615

This fix was made post-4.23 and is in 4.24 M1.  It has also recently been back-ported to the R4_23_maintenance branch.

**Comment by derWallace** [comment]
@jjohnstn Thank you for your hint. I tested with  4.24 M1 and it works again as you described.
