### ISSUE TITLE
Impossible to set a conditional breakpoint in java.io.File(File parent, String child)

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-jdt/eclipse.jdt.debug#273]
Impossible to set a conditional breakpoint in java.io.File(File parent, String child)

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/3462260/cba419b9-6cfd-4289-9d60-a2d24ed062f4)

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/3462260/202b1c38-3483-4d69-9e82-14a070e00818)

When debugging, i get this message :

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/3462260/5f0f823c-e7d5-4b79-b8a8-e68043038958)

This is due to 2 answers for "java.io.File" in org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(ModuleBinding, ModuleBinding[], Function<ModuleBinding, NameEnvironmentAnswer>)

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/3462260/989b46b8-3591-4913-926f-b8ef4132c573)

So "java.io.File" is reported as ambigous

**Comment by SougandhS** [comment]
@mpalat Could you please assign this ticket to me.
