### ISSUE TITLE
wrong jvm detected

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#281]
Whenever i restart eclipse IDE on my Oomphed workspace it adds an JDK 20 as JavaSE-17.
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/5ccc3240-04f5-493b-a0c5-c2d1d759be0f) 
Even though i have an JDK 17 installed. 
I don't mind if it would just adds other installed JDKs but it It should use the 17 JDK for JavaSE-17 and don't change my configuration!

I don't know if that is an OOmph thing or the new JDK autodetection.

**Comment by iloveeclipse** [comment]
> I don't know if that is an OOmph thing or the new JDK autodetection.

You can start Eclipse with new workspace and plugin customization file (`eclipse -pluginCustomization /tmp/pluginCustomization.ini`) that contains this line
```
org.eclipse.jdt.launching/detectVMsAtStartup=false
```
If the same problem appears again, it's not the autodetection, but Oomph.

**Comment by jukzi** [comment]
@merks this is a problem of OOmph- it autoselects a wrong JDK version by default:
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/3f0f6c44-72ed-4209-931c-e4d22ba80094)
Workaround: manually select appropriate version:
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/5f8ba67e-d2ab-41ef-b65a-63adc44e9d1c)

**Comment by merks** [comment]
I don't think this was ever "auto selected".  The selection is remembered though in Navigate -> Open Setup -> User where you can see things like this:

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/208716/7eb98e9f-5deb-44d9-80da-56ce3bef40b8)

**Comment by merks** [comment]
If you change it, it should be remembered after that.  Also, in performing setup tasks, you can always hit Back and use Show All Variables to see what's set and to be able to change what's set.

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/208716/030e283d-8c46-4dd9-8240-a9e4da37f138)

**Comment by iloveeclipse** [comment]
OK, closing this one as this has nothing with jdt.debug.

**Comment by jukzi** [comment]
@merks 
> Navigate -> Open Setup -> User

Here is a Screenshot of the eclipse installation that always switches back to 20:
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/870278c7-bf60-49ff-b139-3ea28c0ad82b)

what is wrong there?

**Comment by merks** [comment]
In that installation if you do Help -> Perform Setup Tasks, press the Back button, and check the Show all variables, what do you see?  If what you see is not what you want, and you change it to what you want, and continue with performing the tasks to completion, does it set it correctly?  If you then repeat the step from the start above, does it show the changed value?

**Comment by merks** [comment]
And now if you repeat the steps, the value in the dialog is wrong again?  That value must have been saved somewhere (must be coming from somewhere)....

**Comment by merks** [comment]
Note that the one the JRE task sets I expect would look like this:

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/208716/7dee842c-312a-473b-a09a-62f91146f3b4)

Because the task names it that way:

![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/208716/a4f0467f-9188-4d03-b967-300d4a780ace)

**Comment by jukzi** [comment]
Meanwhile i restarted eclipse. While eclipse started the JDK in JDT was set to 20 again (why? can't reproduce). But then OOmph automatically switched it to 17:
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/5223c5fe-807f-4e33-9e0b-defc6a704d27)
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/801367e6-b5dc-4d53-91f9-c10d66e1d8e5)

at the moment i can not retry "Perform Setup Tasks" because it always fails with.

`No repository found at https://download.eclipse.org/webtools/CI/3.30.0/I-latest/repository.`

**Comment by merks** [comment]
Your picture is showing it being set to the right value and that thing is the default JRE.    What exactly is being set to 20?  Tme default compliance level?  That might depend on the JRE used to launch the IDE itself?

**Comment by jukzi** [comment]
> No repository found at https://download.eclipse.org/webtools/CI/3.30.0/I-latest/repository.

does this need to be updated to 31?
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a81631d7f0bccb4770dd3c4253733972fd2afb87/oomph/Platform.setup#L801

**Comment by jukzi** [comment]
This was 20 back then before oomph kicked in:
![image](https://github.com/eclipse-jdt/eclipse.jdt.debug/assets/51790620/5c5134d7-1f5d-46c8-82cd-207faad013f6)

**Comment by merks** [comment]
Yes, the setup needs updating:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1215

**Comment by merks** [comment]
That the variable used to record your chosen/desired JRE for jre.location-17 is global, so if you change it anywhere for any setup, all installations/workspaces will switch to that choice the next time setup tasks are performed.

If you want to change differently for some specific workspace or installation, better copy the variable to Navigate -> Open Setup -> Workspace (or Installation), and change it there to override what's in the user.setup.

**Comment by jukzi** [comment]
I can't reproduce this anymore: I tried with both 17 and 20 as 17+ JRE both  times i ended up with a 17 JDK for  jdt, also after restarting.
Thanks though: i learned something about Oomph today :-)
OOmphing works again.
