### ISSUE TITLE
could not found some folder or class file in 3.35.0 than 3.32.0

### ISSUE THREAD

**Issue by Reedon1** [eclipse-jdt/eclipse.jdt.debug#397]
Many classes in org. eclipse. jdt. core are missing in version 3.35.0, such as. Org. eclipse. jdt. internal. compiler. ast; Org. eclipse. jdt. internal. compiler. problem, but there are still packages available in version 3.32.0. Where did these packages go after the version upgrade?

**Comment by Reedon1** [comment]
it has a vulnerable  in org.eclipse.jdt.core for 3.32.0 version , i want to use some class file. example that under this folder, org.eclipse.jdt.internal.compiler.ast, org.eclipse.jdt.internal.compiler.problem, but i could not found this folder when i use 3.35.0 version.

**Comment by akurtakov** [comment]
By the versions you give I would assume you're using Maven artifacts. If that's the case you should be looking https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.36.0 which is even a proper dependency of https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.36.0 . In the past o.e.jdt.core had all of ecj bundled in via a convoluted build system, now it's simpler dependency as it should have always been.

**Comment by iloveeclipse** [comment]
Not a bug, please ask questions in the future at https://github.com/eclipse-jdt/eclipse.jdt.debug/discussions.
