### ISSUE TITLE
Breakpoint cannot be set in anonymous class in chained methods

### ISSUE THREAD

**Issue by apupier** [eclipse-jdt/eclipse.jdt.debug#40]
I failed so far to reproduce with a simpler example

![brekpointNotSetInsideAnonumousClass](https://user-images.githubusercontent.com/1105127/167102017-fa0b49fe-be8d-4996-9148-4a126ce6fc10.gif)

To reproduce:
 - import https://github.com/apupier/camel-quarkus-examples/tree/reproducer-for-jdt-debug/timer-log
 - Open https://github.com/apupier/camel-quarkus-examples/blob/0874fe787c0e7284f97dc56b53fcf1050af92af5/timer-log/src/main/java/org/acme/timer/log/TimerRoute.java
 - Try to set breakpoint on l.31 https://github.com/apupier/camel-quarkus-examples/blob/0874fe787c0e7284f97dc56b53fcf1050af92af5/timer-log/src/main/java/org/acme/timer/log/TimerRoute.java#L31
The breakpoint is set on the first line after the anonymous class

**Comment by iloveeclipse** [comment]
Can you please try latest SDK 4.24 build? 
See https://download.eclipse.org/eclipse/downloads/drops4/I20220505-1800/
I assume the fix for #33 could helped here.
Also please provide a simple standalone example that doesn't need external dependencies.

**Comment by apupier** [comment]
I confirm that it is fixed with latest Integration build

**Comment by iloveeclipse** [comment]
Thanks, good to know.
