### ISSUE TITLE
NoSuchMethodError: org.eclipse.jdt.internal.core.BinaryType.getElementInfo()

### ISSUE THREAD

**Issue by bobfields** [eclipse-jdt/eclipse.jdt.debug#407]
Updated Eclipse JDT Core from 3.19.300.v20231201-0110 to 3.19.400.v20240229-0520.     Enhanced Class Decompiler (Core) is version 3.4.0 for both installations. When debugging and opening source I get:
```
NoSuchMethodError: 'java.lang.Object org.eclipse.jdt.internal.core.BinaryType.getElementInfo()'
at org.sf.feeling.decompiler.editor.DecompilerSourceMapper.findSource(DecompilerSourceMapper.java:61)
```
It looks like that method was removed in the latest update ? It worked before the update. Looks like Eclipse debugger core needs a fix ?
Eclipse running on Windows 10 with all current plugins. 
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)

**Comment by iloveeclipse** [comment]
> It looks like that method was removed in the latest update ? 

It is **overridden** now in BinaryType (signature changed), see 4556ac22b87bd69828fed9fbcf8ce24c24fad2ec

> It worked before the update. Looks like Eclipse debugger core needs a fix ?

Please open a bug for "Enhanced Class Decompiler". JDT project **internal** code is not API and can be changed with any release.

**Comment by bobfields** [comment]
FYI the link to the bug issue in ECD, reported by many many users...
https://github.com/ecd-plugin/ecd/issues/103
