### ISSUE TITLE
[Tests][Java 21] 3 JDT Debug tests are failing consistently with Java 21

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#416]
https://download.eclipse.org/eclipse/downloads/drops4/I20240323-1800/testResults.php

org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests | testDefaultMainWithoutArgs | Failure | Process finished with error code expected:<0> but was:<1>junit.framework.AssertionFailedError: Process finished with error code expected:<0> but was:<1>at junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.failNotEquals(Assert.java:329)at junit.framework.Assert.assertEquals(Assert.java:78)at junit.framework.Assert.assertEquals(Assert.java:234)at junit.framework.TestCase.assertEquals(TestCase.java:377)at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testDefaultMainWithoutArgs(InstanceMainMethodsTests.java:61)at java.base/java.lang.reflect.Method.invoke(Method.java:580)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2726)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:1583) | 1.729
-- | -- | -- | -- | --
org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests | testStaticMainWithoutArgs | Failure | Process finished with error code expected:<0> but was:<1>junit.framework.AssertionFailedError: Process finished with error code expected:<0> but was:<1>at junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.failNotEquals(Assert.java:329)at junit.framework.Assert.assertEquals(Assert.java:78)at junit.framework.Assert.assertEquals(Assert.java:234)at junit.framework.TestCase.assertEquals(TestCase.java:377)at org.eclipse.jdt.debug.tests.launching.InstanceMainMethodsTests.testStaticMainWithoutArgs(InstanceMainMethodsTests.java:45)at java.base/java.lang.reflect.Method.invoke(Method.java:580)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2726)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:1583)

org.eclipse.jdt.debug.tests.variables.DetailFormatterTests | testInfixDetails1 | Failure | The returned value from (true && true \|\| !(false&&true) \|\| !(true==true\|\|true!=true&&true)) should be truejunit.framework.AssertionFailedError: The returned value from (true && true \|\| !(false&&true) \|\| !(true==true\|\|true!=true&&true)) should be trueat junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.assertTrue(Assert.java:22)at junit.framework.TestCase.assertTrue(TestCase.java:192)at org.eclipse.jdt.debug.tests.variables.DetailFormatterTests.testInfixDetails1(DetailFormatterTests.java:246)at java.base/java.lang.reflect.Method.invoke(Method.java:580)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.jdt.debug.tests.AbstractDebugTest.runBare(AbstractDebugTest.java:2726)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at junit.framework.TestSuite.runTest(TestSuite.java:241)at junit.framework.TestSuite.run(TestSuite.java:236)at junit.framework.TestSuite.runTest(TestSuite.java:241)at org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:61)at java.base/java.lang.Thread.run(Thread.java:1583)
-- | -- | -- | --

**Comment by SarikaSinha** [comment]
cc @mpalat @jarthana

**Comment by iloveeclipse** [comment]
Seem to be fixed in the meantime
