### ISSUE TITLE
Update org.eclipse.jdt.launching.javaagent to use ASM 9.7

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#418]
We've missed ASM update to 9.6, and there is already 9.7 available, so we should update to that.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1951 and previous task https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/224.

**Comment by akurtakov** [comment]
This is causing StratumTest failure in I-builds (https://download.eclipse.org/eclipse/downloads/drops4/I20240406-0130/testresults/html/org.eclipse.jdt.debug.tests_ep432I-unit-cen64-gtk3-java22_linux.gtk.x86_64_22.html) . After looking into the details it's that jdt stratum (aka javaagent) is not available on Java 22.
I'll provide PR.

**Comment by akurtakov** [comment]
This one is done.
