### ISSUE TITLE
DELETE key in Breakpoint conditions view deletes breakpoint

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#444]
Editing breakpoint condition's source text: When using the forward "Delete" key (not backspace!) sometimes deletes the whole breakpoint instead of only editing the condition's text

**Comment by jukzi** [comment]
always reproducible: add breakpoint, check "Condition", type some text, press DEL

**Comment by SarikaSinha** [comment]
Yes, this is an old bug.
