### ISSUE TITLE
[win] can not launch java with long classpath containing non-Ascii letter

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#45]
Given a workspace in a path with a non-Ascii letter like "C:\Jörg"
And then try to launch a plain test.Main.main() the command line will be like:
`C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe -classpath C:\Jörg\projectName\test\bin test.Main`  (OK)
but when the classpath gets too long for command line then the class path argument is wrapped in a UTF-8 encoded file like
"argument.txt":
`-classpath C:\Jörg\projectName\test\bin`  (OK)
and the command line will be
`C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\java.exe "@argument.txt" test.Main`  (OK)
that will result in "java.lang.ClassNotFoundException: test.Main"  (NOK)
If i manually convert the argument.txt from UTF8 to ANSI then the command line works. 
The argument file has always to be encoded with the system encoding instead of UTF-8.
see
https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#java-command-line-argument-files
"_The argument file must contain only ASCII characters or characters in **system default encoding** that's ASCII friendly, such as UTF-8._"

Side note: in the launch configuration dialog is a button to show command line. But the copied command line does not directly work: 1. it is missing double quotes around the executable path ("Eclipse Adoptium" contains a white space) 
2. there are line breaks instead of blanks as delimiters.

The error is probably "StandardCharsets.UTF_8" in org.eclipse.jdt.internal.launching.ClasspathShortener.createClassPathArgumentFile(String) and org.eclipse.jdt.internal.launching.ClasspathShortener.createModulePathArgumentFile(String).

from Bug 385738 - Shorten the classpath/modulepath if necessary.

**Comment by jukzi** [comment]
> I wonder if that means UTF-8 is fine because it is ASCII friendly???

they certainly mean, it's ok to use ASCII characters encoded as utf-8. -which is only asubset

**Comment by jukzi** [comment]
I wonder how to get the system encoding?
<18: Charset#defaultCharset() 
>=18: "native.encoding" system property

see
https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/nio/charset/Charset.html#defaultCharset()
Is a java developer realy meant to check the running JVM version?

**Comment by iloveeclipse** [comment]
> Is a java developer realy meant to check the running JVM version?

See https://openjdk.java.net/jeps/400

**Comment by jukzi** [comment]
i do not see a clean solution there. Should we use
Charset.forName("default") 
-> UnsupportedCharsetException -> Charset.forName("native.encoding")
??
