### ISSUE TITLE
many JDI tests fail in IBuilds on Windows

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#508]
![image](https://github.com/user-attachments/assets/1c66817c-79ec-4b21-94eb-535cca32a822)
```
launched with pid=14976: C:\PROGRA~1\ECLIPS~1\jdk-17.0.5.8-hotspot\bin\javaw.exe -classpath C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17\workarea\I20240923-0040\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.jdt.debug.jdi.tests_1.1.100.v20240918-0908 -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=10048,suspend=y,server=y org.eclipse.debug.jdi.tests.program.MainClass
Listening for transport dt_socket at address: 10048
Connected to localhost:10048 after 87ms
launched with pid=12112: C:\PROGRA~1\ECLIPS~1\jdk-17.0.5.8-hotspot\bin\javaw.exe -classpath C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17\workarea\I20240923-0040\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.jdt.debug.jdi.tests_1.1.100.v20240918-0908 -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=10050,suspend=y,server=y org.eclipse.debug.jdi.tests.program.MainClass
ERROR: transport error 202: bind failed: Permission denied
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:734]
Could not contact the VM at localhost:10050 after 5073ms

```
https://download.eclipse.org/eclipse/downloads/drops4/I20240923-0040/testresults/ep434I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.debug.jdi.tests.AutomatedSuite.txt

The port org.eclipse.debug.jdi.tests.AbstractJDITest.fBackEndPort seems to be increased from test to test with +2 until it reaches a forbidden portnumber.

Instead some valid port has to be used.

```
ServerSocket s = new ServerSocket(0);
int port = s.getLocalPort();    // returns the port the system selected
```
https://stackoverflow.com/a/2231491

**Comment by iloveeclipse** [comment]
There are also **many different** Windows only test fails in other test suites. I guess we should ask for Windows machine restart via https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4410

**Comment by jukzi** [comment]
@SougandhS are the failing tests something you could work on? Would be highly appreciated to get the i-Build clean
https://download.eclipse.org/eclipse/downloads/drops4/I20240923-1800/testResults.php

**Comment by SougandhS** [comment]
Will try to fix these all.

**Comment by jukzi** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2877 shows no more errors for jdi on win. godd job
