### ISSUE TITLE
Update org.eclipse.jdt.launching.javaagent to use ASM 9.7.1

### ISSUE THREAD

**Issue by SougandhS** [eclipse-jdt/eclipse.jdt.debug#540]
New version of ASM available - 9.7.1
https://asm.ow2.io/
<img width="664" alt="image" src="https://github.com/user-attachments/assets/164a0fcb-5649-451e-8236-e8eccabd00ec">

-- Will upgrade it

**Comment by jukzi** [comment]
thanks @SougandhS
