### ISSUE TITLE
Move JDT Debug plugins(remaining 3) to Java 11 BREE

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#61]
/org.eclipse.jdt.launching.javaagent
/org.eclipse.jdt.launching.macosx
/org.eclipse.jdt.launching.ui.macosx

Should move to Java 11 BREE

https://github.com/eclipse/tycho/issues/1003

**Comment by merks** [comment]
I assume the following is an unintended consequence of this change:

https://www.eclipse.org/forums/index.php/mv/msg/1112218/1856754/#msg_1856754

**Comment by iloveeclipse** [comment]
Yes, most likely. The solution is to use older Eclipse to debug such old JVM.

**Comment by H-Lo** [comment]
Is there a chance to make it work with new Eclipse to avoid having Eclipse instance per project?
