### ISSUE TITLE
stale branches

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.debug#78]
hi JDT, would you mind to clean up stale branches. especially such with confusing names like
"for-master", "for/master" 
https://github.com/eclipse-jdt/eclipse.jdt.debug/branches/stale

**Comment by SarikaSinha** [comment]
@sravanlakkimsetti 
Is it ok to delete? 

From my side, +1 to delete these stale branches.

**Comment by sravanlakkimsetti** [comment]
+1 from my side as well. Be careful and do not delete branches related to beta java work and maintenance branches. Some of them will be reported as stale. but should not be deleted

**Comment by SarikaSinha** [comment]
@jukzi 
I don't see branches named: "for-master", "for/master".
https://github.com/eclipse-jdt/eclipse.jdt.debug/branches/stale


Planning to delete these stale branches :
Jared_Breakpoints
unlabeled-1.1.2
unlabeled-1.9.2
STABLE
jdt_debug_Patch_12/18
debug-milestone-2
debug-milestone-3
debug-milestone-4
Debug-M5
JDK_1_5
J2SE5_Connectors
test_failures
bug82587
integration

**Comment by sravanlakkimsetti** [comment]
+1 from my side

**Comment by SarikaSinha** [comment]
Done!

**Comment by jukzi** [comment]
> I don't see branches named: "for-master", "for/master".

looks like @iloveeclipse deleted it yeterday :
```
{
    "id": "22498314308",
    "type": "DeleteEvent",
    "actor": {
      "id": 964108,
      "login": "iloveeclipse",
      "display_login": "iloveeclipse",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iloveeclipse",
      "avatar_url": "https://avatars.githubusercontent.com/u/964108?"
    },
    "repo": {
      "id": 476635884,
      "name": "eclipse-jdt/eclipse.jdt.debug",
      "url": "https://api.github.com/repos/eclipse-jdt/eclipse.jdt.debug"
    },
    "payload": {
      "ref": "for-master",
      "ref_type": "branch",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2022-06-23T09:30:46Z",
    "org": {
      "id": 102054714,
      "login": "eclipse-jdt",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/eclipse-jdt",
      "avatar_url": "https://avatars.githubusercontent.com/u/102054714?"
    }
  }
```
https://api.github.com/repos/eclipse-jdt/eclipse.jdt.debug/events?page=2

> Done!

thanks
