### ISSUE TITLE
Update JDT launching to ASM 9.3

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.debug#8]
ASM 9.3 is released, with support for Java 19.
See https://asm.ow2.io/versions.html#9.3

We should update JDT to use it, once the bundle is in Orbit, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=579574

Related bug for PDE is https://github.com/eclipse-pde/eclipse.pde.ui/issues/11

**Comment by mickaelistria** [comment]
Done with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/8f79635e7217ecb24dbc209b964711e66a8f322d
