### ISSUE TITLE
JDT produces nested argfiles, which Java doesn't support

### ISSUE THREAD

**Issue by nmishkin** [eclipse-jdt/eclipse.jdt.debug#84]
When launching a configuration with "Use @argfile" enabled, it appears to be the case that if the Java command line being generated by the JDT is sufficiently long, the generated argfile itself contains a reference to yet another generated argfile. However, AFAICT Java doesn't supported nested argfiles like this.

**Comment by nmishkin** [comment]
See the attached [tarfile](https://github.com/eclipse-jdt/eclipse.jdt.core/files/9121535/dummy.tar.gz) of a project that exhibits the behavior. But really it's simply a matter of making a run config with a large-enough amount of stuff in the "VM arguments" section.

When I launch the configuration I get this in the Console view:

```
Error: Could not find or load main class @.Users.nmishkin.Documents.workspace_Repos_newton5.dummy..temp-Dummy-classpath-arg-1657894011167.txt
Caused by: java.lang.ClassNotFoundException: @/Users/nmishkin/Documents/workspace_Repos_newton5/dummy//temp-Dummy-classpath-arg-1657894011167/txt
```

If instead of launching the configuration I do "Show command line" I get a command line like:

```
/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/bin/java @/Users/nmishkin/Documents/workspace_Repos_newton5/dummy/.temp-Dummy-args-1657895344160.txt
```
Here's the argfile named above: [temp-Dummy-args-1657895344160.txt](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/9122049/temp-Dummy-args-1657895344160.txt). It contains this:

```
@/Users/nmishkin/Documents/workspace_Repos_newton5/dummy/.temp-Dummy-classpath-arg-1657895344159.txt
```
Here's the argfile named above: [temp-Dummy-classpath-arg-1657895344159.txt](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/9122055/temp-Dummy-classpath-arg-1657895344159.txt).

**Comment by iloveeclipse** [comment]
Thanks for example. This is a regression from https://bugs.eclipse.org/bugs/show_bug.cgi?id=565902.
Here is the [original feature request](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8027634) where the argfile support for java was introduced.
The added [Oracle's tool guide](https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-4856361B-8BFD-4964-AE84-121F5F6CF111) explicitly states: 

> Use of the at sign (@) to recursively interpret files isn’t supported.

That was obviously not considered while [bug 565902](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565902) patching.

I will push a patch in a moment.
