### ISSUE TITLE
[19] org.eclipse.jdt.debug.tests.eval.Java9Tests.testBug575039_methodBreakpointOnJavaBaseModuleClass_expectSuccessfulEval() fails with Java 19

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.debug#92]
@gayanper 
https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/89
The test added fails with Java 19.
Right now I have just made the changes for it to not run till Java 18.
Can you look into that and change the test accordingly?

**Comment by gayanper** [comment]
Sure i can have a look

**Comment by SarikaSinha** [comment]
Will merge the change to Beta after M2 release.
Thanks Gayan.
