### ISSUE TITLE
Eclipse can't run if classpath is too large and if launch config name is too long

### ISSUE THREAD

**Issue by stas-bob** [eclipse-jdt/eclipse.jdt.debug#97]
I have a junit test with a large classpath. I can run it once and it works. If I re-run the test from the junit view, eclipse creates a LaunchConfig with the name "Rerun typename.testname" and .temp file which contains the classpath. The .temp file's name has the full name of the launch config included. The launch failes with

"
Error: could not open `C:\Users\XXX\repos\yyy\yyy-assistant\yyy-bundles\cccc-bundle\.temp-Rerun com.my.type.bundles.xy.gen.XxxxyyyTest.test000_XxxyyyScenario_SetVolumeOKSetVolumeUnspecificUnder80PercentsetVolumeLevel_SetMediaVolumeTo16-classpath-arg-1659449408103.txt'
"
I guess it failes, because in the generated command line

javaw "@filepath_from_above" ... the filepath_from_above is too long

Reproducible on windows.

Imo,
org.eclipse.jdt.internal.launching.ClasspathShortener.shortenClasspathUsingClasspathArgumentFile(int)
must shorten the created file name. Is there any reason, why taking the launch config name entirtly? You might prune it to max 10 characters or so.

**Comment by Shee43** [comment]
Can you please provide the steps to reproduce the issue

**Comment by stas-bob** [comment]
[TestProj.zip](https://github.com/eclipse-jdt/eclipse.jdt.debug/files/10910802/TestProj.zip)
![grafik](https://user-images.githubusercontent.com/293153/223461528-bfc75ef8-5613-416a-9bee-4787f425f8a5.png)

**Comment by Shee43** [comment]
We understand the problem but not able to reproduce this. Can you either create a video or provide exact steps. We are not  seeing the Rerun coming.

**Comment by stas-bob** [comment]
I could not reproduce it aswell if placed TestProject under C:\. The path needs to be longer. See video

https://user-images.githubusercontent.com/293153/224277257-8171e346-c608-4b32-bcf8-ed524bf3fa1d.mp4

**Comment by stas-bob** [comment]
The obvious solution is not having a long path for the project. But I dont understand
- why is the first test execution ok but the later is not
- the file name of the .temp is derived from the test name. But if the test name is long, the test execution fails. So could you give the file name some arbitary shot name and somewhat ease the long path problem?

**Comment by trancexpress** [comment]
> But I dont understand
>     * why is the first test execution ok but the later is not

Likely the first launch configuration is created on-the-fly, saved to the file and then executed. The 2nd execution tries to use the stored information in the file?

**Comment by stas-bob** [comment]
I didnt debug it to that extent, but it feeld weird because as a user, i dont why the behaviour is diffrent

**Comment by Shee43** [comment]
This is verified in latest Integration Build
